### ISSUE TITLE
-C format option 

### ISSUE THREAD

**Issue by rwhetten** [EdwardsLabProjects/sequence-alignment-tools#2]
I'm trying to use the -C option to reset the format so all information except the sequence is on the FASTA header line of the output file, but the primer_match program is ignoring the option and writing output in the default format. My command line option is `-C ">%P_%h:%s-%e_%d\n %T\n %A\n %Q\n"` and the intended FASTA header output format is ">primerID_scaffoldID:start-end_editdist".
I downloaded the Linux executable from the Releases page today. `primer_match -v` returns a string including the date and time, plus `Release Tag: $Name $`, if that helps.

**Comment by rwhetten** [comment]
Problem solved - using the option `-A ">%P_%h:%s-%e_%d\n %T\n %A\n %Q\n"` produces the intended change in alignment output formatting.

**Comment by edwardsnj** [comment]
Yep, -C is for the *count* output format, -A is for the "alignment" output format. Glad you figured it out!
