### ISSUE TITLE
incorporation of multithreading option

### ISSUE THREAD

**Issue by sanyalab** [EdwardsLabProjects/sequence-alignment-tools#3]
Hello,

Love this tool and the well thought output features. I was wondering if there was a way to incorporate multithreading. This will be useful to search for primers/motifs in several thousand bacterial genomes.

Thanks
Abhijit

**Comment by edwardsnj** [comment]
Thank you for your interest in these tools. Threading would be a lot of work, when you can get trivial concurrency by partitioning your databases or primers.

**Comment by sanyalab** [comment]
Yes I know how to do that. Was trying to save some time partitioning. Thanks.
